---
language: generic
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-26.3-travis
install:
  - true Download and install emacs version manager
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - true Install emacs to test
  - evm list
  - evm install $EVM_EMACS --use --skip
  - true Install cask and dependencies
  - CASK_EMACS=$EVM_EMACS
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - PATH=$PATH:$HOME/.cask/bin
script:
  - emacs --version
  - cask install
  - cask exec ert-runner
after_success:
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - env: [ omnilint ]
      language: generic
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
      after_success: true
