---
name: CI
on: [ push, pull_request ]
jobs:
  lint:
    strategy:
      matrix:
        checker:
          - load-file
          - byte-compile
          - package-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@v3.0
        with:
          version: 25.1
      - uses: leotaku/elisp-check@v1.1
        with:
          check: ${{ matrix.checker }}
          file: counshell.el
          warnings_as_errors: true
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@v3.0
        with:
          version: 25.1
      - uses: leotaku/elisp-check@v1.1
        with:
          check: ert
          file: test/counshell-test.el
          warnings_as_errors: true
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/omnilint:v0.2
